CREATE TABLE animal (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   provisional_name VARCHAR(255) NOT NULL,
   estimated_age INT NOT NULL,
   breed VARCHAR(255) NOT NULL,
   entry_date date NOT NULL,
   adoption_date date,
   entry_condition VARCHAR(255) NOT NULL,
   adopted_name VARCHAR(255),
   date_of_death date,
   animal_size VARCHAR(255) NOT NULL,
   CONSTRAINT pk_animal PRIMARY KEY (id)
);